import React, { useState, useEffect } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '../ui/card';
import { Button } from '../ui/button';
import { ArrowLeft, FileText, Download, Calendar, DollarSign, TrendingUp, Users } from 'lucide-react';
import { dailySalesAPI, dutyAPI, workerAPI } from '../../utils/api';
import { toast } from 'sonner';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface ReportsProps {
  station: any;
  token: string;
  onBack: () => void;
}

export default function Reports({ station, token, onBack }: ReportsProps) {
  const [loading, setLoading] = useState(true);
  const [reportData, setReportData] = useState({
    totalSales: 0,
    totalDuties: 0,
    totalWorkers: 0,
    monthlyRevenue: 0
  });

  useEffect(() => {
    fetchReportData();
  }, []);

  const fetchReportData = async () => {
    setLoading(true);
    try {
      const [salesResponse, dutiesResponse, workersResponse] = await Promise.all([
        dailySalesAPI.getDailySales(),
        dutyAPI.getAllDuties(),
        workerAPI.getWorkers()
      ]);

      const sales = Array.isArray(salesResponse.data) ? salesResponse.data : [];
      const duties = Array.isArray(dutiesResponse.data) ? dutiesResponse.data : [];
      const workers = Array.isArray(workersResponse.data) ? workersResponse.data : [];

      const totalSales = sales.reduce((sum, sale) => sum + parseFloat(sale.total || 0), 0);
      const activeWorkers = workers.filter(w => w.is_active && w.role !== 'admin').length;

      setReportData({
        totalSales,
        totalDuties: duties.length,
        totalWorkers: activeWorkers,
        monthlyRevenue: totalSales
      });
    } catch (error) {
      console.error('Error fetching report data:', error);
      toast.error('Failed to load report data');
    } finally {
      setLoading(false);
    }
  };

  const generateReport = () => {
    const doc = new jsPDF();
    const primary = station.theme.primaryColor || '#2563eb';

    // Header
    doc.setFontSize(18);
    doc.setTextColor(primary);
    doc.text(station.name, 14, 18);
    doc.setFontSize(11);
    doc.setTextColor('#333333');
    doc.text(station.brand, 14, 25);
    doc.text(station.address, 14, 31);

    // Report Title
    doc.setFontSize(14);
    doc.setTextColor(primary);
    doc.text('Station Performance Report', 14, 42);

    // Report Info
    doc.setFontSize(11);
    doc.setTextColor('#333333');
    doc.text(`Generated: ${new Date().toLocaleDateString('en-IN')}`, 14, 50);
    doc.text(`Generated by: Manager Dashboard`, 14, 56);
    doc.text(`Report Period: Current Operations`, 14, 62);

    // Summary Table
    const summaryData = [
      ['Total Sales Revenue', `₹${reportData.totalSales.toLocaleString()}`],
      ['Total Duties Completed', `${reportData.totalDuties}`],
      ['Active Workers', `${reportData.totalWorkers}`],
      ['Monthly Revenue', `₹${reportData.monthlyRevenue.toLocaleString()}`]
    ];

    autoTable(doc, {
      head: [['Metric', 'Value']],
      body: summaryData,
      startY: 68,
      styles: { fontSize: 10 },
      headStyles: { fillColor: primary },
      columnStyles: {
        0: { cellWidth: 80 },
        1: { cellWidth: 60, halign: 'right' }
      }
    });

    const tableEndY = (doc as any).lastAutoTable?.finalY || 100;
    let y = tableEndY + 15;

    // Performance Metrics
    doc.setFontSize(12);
    doc.setTextColor(primary);
    doc.text('Performance Analysis', 14, y);
    y += 8;
    
    doc.setFontSize(10);
    doc.setTextColor('#333333');
    const avgSalesPerDuty = reportData.totalDuties > 0 ? (reportData.totalSales / reportData.totalDuties) : 0;
    const avgSalesPerWorker = reportData.totalWorkers > 0 ? (reportData.totalSales / reportData.totalWorkers) : 0;
    
    doc.text(`Average Sales per Duty: ₹${avgSalesPerDuty.toFixed(2)}`, 14, y);
    y += 6;
    doc.text(`Average Sales per Worker: ₹${avgSalesPerWorker.toFixed(2)}`, 14, y);
    y += 6;
    doc.text(`Worker Utilization: ${reportData.totalWorkers > 0 ? '100%' : '0%'}`, 14, y);

    // Footer
    doc.setFontSize(8);
    doc.setTextColor('#666666');
    doc.text('Generated by PumpMate Management System', 14, 280);
    doc.text(`Report ID: RPT-${Date.now()}`, 14, 285);
    
    // Save PDF
    const filename = `pumpmate-performance-report-${new Date().toISOString().split('T')[0]}.pdf`;
    doc.save(filename);
    
    toast.success('Professional PDF report downloaded successfully!');
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center gap-4">
        <Button variant="outline" size="sm" onClick={onBack}>
          <ArrowLeft className="h-4 w-4 mr-2" />
          Back
        </Button>
        <div>
          <h2 className="text-3xl font-bold">Reports</h2>
          <p className="text-gray-500 mt-1">Station performance and analytics</p>
        </div>
      </div>

      {loading ? (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
          {[1, 2, 3, 4].map(i => (
            <div key={i} className="h-32 bg-gray-200 rounded-lg animate-pulse"></div>
          ))}
        </div>
      ) : (
        <>
          {/* Summary Cards */}
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
            <Card>
              <CardContent className="p-6">
                <div className="flex items-center gap-3">
                  <div className="p-2 bg-green-100 rounded-lg">
                    <DollarSign className="h-6 w-6 text-green-600" />
                  </div>
                  <div>
                    <p className="text-sm text-gray-600">Total Sales</p>
                    <p className="text-2xl font-bold">₹{reportData.totalSales.toLocaleString()}</p>
                  </div>
                </div>
              </CardContent>
            </Card>

            <Card>
              <CardContent className="p-6">
                <div className="flex items-center gap-3">
                  <div className="p-2 bg-blue-100 rounded-lg">
                    <Calendar className="h-6 w-6 text-blue-600" />
                  </div>
                  <div>
                    <p className="text-sm text-gray-600">Total Duties</p>
                    <p className="text-2xl font-bold">{reportData.totalDuties}</p>
                  </div>
                </div>
              </CardContent>
            </Card>

            <Card>
              <CardContent className="p-6">
                <div className="flex items-center gap-3">
                  <div className="p-2 bg-purple-100 rounded-lg">
                    <Users className="h-6 w-6 text-purple-600" />
                  </div>
                  <div>
                    <p className="text-sm text-gray-600">Active Workers</p>
                    <p className="text-2xl font-bold">{reportData.totalWorkers}</p>
                  </div>
                </div>
              </CardContent>
            </Card>

            <Card>
              <CardContent className="p-6">
                <div className="flex items-center gap-3">
                  <div className="p-2 bg-orange-100 rounded-lg">
                    <TrendingUp className="h-6 w-6 text-orange-600" />
                  </div>
                  <div>
                    <p className="text-sm text-gray-600">Monthly Revenue</p>
                    <p className="text-2xl font-bold">₹{reportData.monthlyRevenue.toLocaleString()}</p>
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>

          {/* Report Actions */}
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <FileText className="h-5 w-5" />
                Generate Reports
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <p className="text-gray-600">
                Download comprehensive reports for your fuel station operations.
              </p>
              
              <div className="flex gap-4">
                <Button 
                  onClick={generateReport}
                  className="gap-2"
                  style={{ backgroundColor: station.theme.primaryColor }}
                >
                  <Download className="h-4 w-4" />
                  Download PDF Report
                </Button>
              </div>
            </CardContent>
          </Card>
        </>
      )}
    </div>
  );
}